name: my_team
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.3.0+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  cloud_firestore: ^4.9.1
  uuid: ^4.0.0
  intl: ^0.18.1
  pin_code_text_field: ^1.8.0
  flutter_screenutil: ^5.7.0
  google_fonts: ^4.0.4
  flutter_advanced_switch: ^3.0.1  
  rounded_loading_button: ^2.1.0
  clipboard: ^0.1.3
  share_plus: ^6.0.1
  flutter_utility: ^0.0.2

  stream_video_flutter: ^0.3.2
  stream_video:
  dart_jwt_token: ^0.0.3

  platform: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo.png"

flutter:

  uses-material-design: true

  assets:
    - images/
